version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: voting-mongo
    ports:
      - "27017:27017"

  api:
    build: ./api
    container_name: voting-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: voting-frontend
    ports:
      - "3000:80"
    depends_on:
      - api